// Command rabbit-tf-import emits Terraform `import` blocks for every group
// in a Rabbit domain. Pair it with `terraform plan -generate-config-out=…`
// to bulk-import an existing Rabbit access setup into Terraform.
//
// Usage:
//
//	rabbit-tf-import --domain acme.com > imports.tf
//	terraform plan -generate-config-out=generated.tf
//	terraform apply         # no-op; state now matches reality
//
// Authentication mirrors the provider: ADC by default, with --credentials
// and --impersonate-service-account knobs that match the provider's
// `credentials` / `impersonate_service_account` attributes.
package main

import (
	"context"
	"flag"
	"fmt"
	"io"
	"net/http"
	"os"
	"regexp"
	"sort"
	"strings"

	"github.com/followrabbit-ai/terraform-provider-rabbit/internal/client"
)

func main() {
	if err := run(os.Args[1:], os.Stdout, os.Stderr); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(args []string, stdout, stderr io.Writer) error {
	fs := flag.NewFlagSet("rabbit-tf-import", flag.ContinueOnError)
	fs.SetOutput(stderr)

	domain := fs.String("domain", os.Getenv("RABBIT_DOMAIN_ID"), "Rabbit domain to import (e.g. acme.com). Env: RABBIT_DOMAIN_ID")
	endpoint := fs.String("endpoint", firstNonEmpty(os.Getenv("RABBIT_ENDPOINT"), client.DefaultEndpoint), "Rabbit API endpoint. Env: RABBIT_ENDPOINT")
	audience := fs.String("audience", firstNonEmpty(os.Getenv("RABBIT_AUDIENCE"), client.DefaultAudience), "OAuth2 client ID used as the ID token audience. Env: RABBIT_AUDIENCE")
	credentials := fs.String("credentials", firstNonEmpty(os.Getenv("GOOGLE_CREDENTIALS"), os.Getenv("GOOGLE_APPLICATION_CREDENTIALS")), "Service account JSON file or inline JSON. Env: GOOGLE_CREDENTIALS / GOOGLE_APPLICATION_CREDENTIALS")
	impersonate := fs.String("impersonate-service-account", os.Getenv("GOOGLE_IMPERSONATE_SERVICE_ACCOUNT"), "Service account email to impersonate via Google IAM Credentials. Env: GOOGLE_IMPERSONATE_SERVICE_ACCOUNT")
	output := fs.String("output", "-", "Output file path; \"-\" for stdout")
	resourcePrefix := fs.String("resource-prefix", "", "Prefix prepended to every generated Terraform resource name (useful when multiple domains land in the same module)")
	includeMembers := fs.Bool("include-members", false, "Also emit `rabbit_group_member` import blocks for every existing principal. Off by default because `rabbit_group` is already authoritative for its principal list — only use this when you want each principal managed as a separate additive resource (e.g. spread across modules).")

	if err := fs.Parse(args); err != nil {
		return err
	}
	if *domain == "" {
		fs.Usage()
		return fmt.Errorf("--domain is required")
	}

	ctx := context.Background()

	httpC, err := buildHTTPClient(ctx, *audience, *credentials, *impersonate)
	if err != nil {
		return fmt.Errorf("auth: %w", err)
	}

	c, err := client.New(client.Config{
		Endpoint:  *endpoint,
		DomainID:  *domain,
		HTTP:      httpC,
		UserAgent: "rabbit-tf-import",
	})
	if err != nil {
		return fmt.Errorf("client: %w", err)
	}

	groups, err := c.ListGroups(ctx, *domain)
	if err != nil {
		return fmt.Errorf("list groups in %q: %w", *domain, err)
	}
	// Stable output order is important for review-friendly diffs.
	sort.Slice(groups, func(i, j int) bool {
		if groups[i].Name == groups[j].Name {
			return groups[i].ID < groups[j].ID
		}
		return groups[i].Name < groups[j].Name
	})

	w := stdout
	if *output != "-" {
		f, err := os.Create(*output)
		if err != nil {
			return fmt.Errorf("open output: %w", err)
		}
		defer f.Close()
		w = f
	}

	emit(w, *domain, *resourcePrefix, groups, *includeMembers)
	return nil
}

// buildHTTPClient mirrors the provider's auth chain. As a convenience, when
// RABBIT_TEST_IMPERSONATE_SA_EMAIL is set, it uses Rabbit's bespoke
// impersonation (matching the acceptance test path) — handy for dev / demo
// tenants where standard ADC can't authenticate as a non-employee.
func buildHTTPClient(ctx context.Context, audience, credentials, impersonate string) (*http.Client, error) {
	if os.Getenv("RABBIT_TEST_IMPERSONATE_SA_EMAIL") != "" && os.Getenv("RABBIT_TEST_IMPERSONATE_TARGET_EMAIL") != "" {
		return client.NewRabbitImpersonationHTTPClient(ctx, "", "")
	}
	authCfg := client.AuthConfig{
		Audience:                  audience,
		ImpersonateServiceAccount: impersonate,
	}
	if credentials != "" {
		if credentials[0] == '{' {
			authCfg.CredentialsJSON = credentials
		} else {
			authCfg.CredentialsFile = credentials
		}
	}
	return client.NewHTTPClient(ctx, authCfg)
}

// emit writes Terraform `import` blocks. The output is deterministic so
// re-runs produce review-friendly diffs.
func emit(w io.Writer, domain, prefix string, groups []client.Group, includeMembers bool) {
	fmt.Fprintf(w, "# Generated by rabbit-tf-import for domain %q.\n", domain)
	fmt.Fprintln(w, "# To materialise the resource HCL alongside these imports, run:")
	fmt.Fprintln(w, "#   terraform plan -generate-config-out=generated.tf")
	fmt.Fprintln(w, "# then review generated.tf, move it into your module, and `terraform apply`")
	fmt.Fprintln(w, "# (the apply should be a no-op — state will already match reality).")
	fmt.Fprintln(w)

	used := map[string]int{}
	for _, g := range groups {
		addr := uniqueAddr("rabbit_group", prefix+slug(g.Name), used)
		fmt.Fprintf(w, "import {\n  to = %s\n  id = %q\n}\n\n", addr, domain+"/"+g.ID)
		if includeMembers {
			memberUsed := map[string]int{}
			// Stable order within a group too.
			ps := make([]client.Principal, len(g.Principals))
			copy(ps, g.Principals)
			sort.Slice(ps, func(i, j int) bool {
				if ps[i].PrincipalType == ps[j].PrincipalType {
					return ps[i].Name < ps[j].Name
				}
				return ps[i].PrincipalType < ps[j].PrincipalType
			})
			for _, p := range ps {
				memberAddr := uniqueAddr("rabbit_group_member", prefix+slug(g.Name)+"_"+slug(p.Name), memberUsed)
				importID := fmt.Sprintf("%s/%s/%s/%s", domain, g.ID, p.PrincipalType, p.Name)
				fmt.Fprintf(w, "import {\n  to = %s\n  id = %q\n}\n\n", memberAddr, importID)
			}
		}
	}
}

var slugStripRE = regexp.MustCompile(`[^a-z0-9_]+`)

// slug turns a free-form name into a Terraform-safe resource label.
func slug(s string) string {
	s = strings.ToLower(s)
	s = slugStripRE.ReplaceAllString(s, "_")
	s = strings.Trim(s, "_")
	if s == "" {
		return "g"
	}
	if s[0] >= '0' && s[0] <= '9' {
		s = "_" + s
	}
	return s
}

// uniqueAddr returns "kind.label", appending a numeric suffix on collision.
func uniqueAddr(kind, label string, seen map[string]int) string {
	base := kind + "." + label
	seen[base]++
	if seen[base] == 1 {
		return base
	}
	return fmt.Sprintf("%s_%d", base, seen[base])
}

func firstNonEmpty(vs ...string) string {
	for _, v := range vs {
		if v != "" {
			return v
		}
	}
	return ""
}
